### ISSUE TITLE
Support types.image.gradient.linear-gradient

### ISSUE THREAD

**Issue by pkudryashov** [3846masa/stylelint-browser-compat#880]
With `"@mdn/browser-compat-data": "5.6.23"` i have the following errors
  - No information was found for "types.image.gradient.linear-gradient" feature.
  - No information was found for "types.image.gradient.linear-gradient.to" feature.
  - No information was found for "types.image.gradient.radial-gradient" feature.

```css
.some-class {
  background: linear-gradient(to top, #dadada, #dadada, #dadada, rgba(0, 0, 0, 0));
}
.some-class2 {
  background-image: radial-gradient(circle, #ccc 0.5px, rgba(0, 0, 0, 0) 1px);
}
```
